Branch otsuka
KazuakiKoiso/ApiServerWinExe pull request #7
Opened 2024-01-16 13:53 UTC by Hiroto-Otsuka

2024-01-17 07:44 UTC, KazuakiKoiso requested changes

2024-01-17 07:44 UTC, KazuakiKoiso commented on ApiServerWinExe/FrmMain.Designer.cs
> +            this.clmIp.Width = 120;
列幅をもう少しギリギリまで縮めてください

2024-01-17 07:44 UTC, KazuakiKoiso commented on ApiServerWinExe/frmMain.cs
> +        private void LvLog_AutoScroll()
<オブジェクト名>_<イベント名>のようなスネーク形式の命名は、VisualStudioが自動で出力するイベントハンドラのメソッドのみです。メソッド名を`AutoScroll`としてください。

2024-01-17 07:44 UTC, KazuakiKoiso commented on ApiServerWinExe/frmMain.cs
> +                lvLog.Focus();
自動スクロール時、フォーカスまで移動する必要はありません。
フォーカスを移動しないと選択行の色が表示されないのは承知していますがそこまでの必要はありません。
フォーカスを移動しないと不都合がある場合はご連絡ください。

2024-01-30 14:21 UTC, Hiroto-Otsuka commented on ApiServerWinExe/FrmMain.Designer.cs
> +            this.clmIp.Width = 120;
this.clmIp.Width = 100で対応しました！

2024-01-30 14:22 UTC, Hiroto-Otsuka commented on ApiServerWinExe/frmMain.cs
> +                lvLog.Focus();
フォーカスを移動しないといけない不都合等はないので、lvLog.Focus();を削除しました。

2024-01-30 14:28 UTC, KazuakiKoiso approved these changes
すべての指摘の対応を確認しました。ありがとうございます。

2024-01-30 14:28 UTC, merged